services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlsrv_quanlysach
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BookM@nager2025!"
    volumes:
      - sql_data:/var/opt/mssql     

volumes:
  sql_data: